### ISSUE TITLE
{Error}:assert failed: WARNING: FAIL TO READ current language FROM main.js!

### ISSUE THREAD

**Issue by Ghost-Cavendish** [tswwe/excalipatch#1]
运行报错如下，大佬帮看下怎么回事：
>>> Locating js file: main.js
>>> Preparing output location: main.js.patched1
>>> Preparing UI language: zh-CN
>>> Preparing button name: 中文手写
>>> Preparing font file: chinese
>>> Preparing icon file: cnHandIcon
>>> Applying patch...
{File}:lib\core\mainjs.aardio
{Line}:#13
{Error}:assert failed: WARNING: FAIL TO READ current language FROM main.js!

To open issues or pull requests, please visit excalipatch reposity: https://github.com/tswwe/excalipath
Press any key to exit...

文件所在目录：
![image](https://user-images.githubusercontent.com/56330712/148739423-dfc23648-b0f7-45e5-8354-edda0b9e8710.png)

**Comment by Ghost-Cavendish** [comment]
> 

![1641804925(1)](https://user-images.githubusercontent.com/56330712/148739759-91176d85-86c1-4e46-bd65-9648f8f42a95.png)

**Comment by tswwe** [comment]
@jk110 你好，能否上传一下你原来的 `main.js` 文件，我等会排查一下

**Comment by Ghost-Cavendish** [comment]
[main.js.txt](https://github.com/tswwe/excalipatch/files/7838827/main.js.txt)
改下后缀

**Comment by tswwe** [comment]
@jk110 你好，麻烦再提供一下同目录的 `data.json` 和 `manifest.json` 文件。
（你可以试试直接打包成zip，就不用修改后缀了）

**Comment by Ghost-Cavendish** [comment]
所有文件
[obsidian-excalidraw-plugin.zip](https://github.com/tswwe/excalipatch/files/7839118/obsidian-excalidraw-plugin.zip)

**Comment by tswwe** [comment]
你好，我看到你的 Obsidian 和 obsidian-excalidraw-plugin 是比较旧的0.12.0 和 1.3.16版本（有什么特别的原因吗？），而我写的工具是在目前最新的 0.12.16 和 1.5.15 版本下工作的，因此无法识别差异较大的旧版 `main.js`。建议你升级到最新版本后再尝试一下。

**Comment by Ghost-Cavendish** [comment]
非常感谢您的帮助，我更新到最新的版本还是不行，能否在排查下
[obsidian-excalidraw-plugin.zip](https://github.com/tswwe/excalipatch/files/7843288/obsidian-excalidraw-plugin.zip)

**Comment by tswwe** [comment]
你好，根据你提供的文件显示，你的 obsidian-excalidraw-plugin 插件并不是目前的最新版本，是不是因为你的 Obsidian 版本太旧了？请检查一下其是否为最新版：
![image](https://user-images.githubusercontent.com/36465489/148881379-f4721685-ce11-4e02-bd10-fd837c59146f.png)

如果不是，请尝试先更新你的 Obsidian 到最新版，然后再更新 obsidian-excalidraw-plugin 插件到真正的最新版。

**Comment by Ghost-Cavendish** [comment]
![image](https://user-images.githubusercontent.com/56330712/148881823-67a9d12e-1ddd-4ed6-84a4-f9f2be4ccb5a.png)
![image](https://user-images.githubusercontent.com/56330712/148881866-1a152953-b161-419f-b5f7-e596888f020a.png)
更新了的啊
好奇怪哦

**Comment by tswwe** [comment]
确实有点奇怪，你上传的描述文件里显示的是1.3.16版本：
![image](https://user-images.githubusercontent.com/36465489/148882609-f255ad91-82da-4c4a-aec5-85f17129d41c.png)
要不先尝试删除并重新安装 obsidian-excalidraw-plugin（以防不测，可以先备份整个obsidian-excalidraw-plugin目录），再用 excalipatch （已更新到0.0.3，也请一并更新）？

**Comment by Ghost-Cavendish** [comment]
![image](https://user-images.githubusercontent.com/56330712/148884257-bbdc22f5-d051-4d19-8280-23c86c8f77aa.png)
额，我找到问题所在了，但是又遇到新的问题，替换后我的插件不能启动了

**Comment by Ghost-Cavendish** [comment]
你能帮我看下是字体的原因吗
[xxx.zip](https://github.com/tswwe/excalipatch/files/7843854/xxx.zip)

**Comment by Ghost-Cavendish** [comment]
[obsidian-excalidraw-plugin.zip](https://github.com/tswwe/excalipatch/files/7843856/obsidian-excalidraw-plugin.zip)
我的插件

**Comment by tswwe** [comment]
字体没问题，你用的 Excalipatch 版本是 0.0.1，已经过期了，请到[发行版页面](https://github.com/tswwe/excalipatch/releases/tag/v0.0.3)下载最新的 0.0.3 后再修补。

**Comment by Ghost-Cavendish** [comment]
![image](https://user-images.githubusercontent.com/56330712/148885319-b1ae11aa-35ae-49da-9e08-44fdc1a8b43a.png)
额，我这个字体没生效？

**Comment by tswwe** [comment]
要先在顶部工具栏选择文本工具，才能在左侧弹出的选项栏里看到多出来的中文字体按钮。

**Comment by Ghost-Cavendish** [comment]
非常感谢👍👍👍
